server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABAE}
    driver-class-name: org.postgresql.Driver
    username: ${PGUSER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: meteodata
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
amqp:
  save-temperature-queue: save-temperature
  get-temperature-statistics-queue: get-temperature