server:
  port: 8091
spring:
  rabbitmq:
    template:
      routing-key: temperaturedata
      exchange: meteodata_exchange
      default-receive-queue: temperaturedata
    listener:
      simple:
        auto-startup: false