server:
  port: 8091
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: temperature
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
    host: localhost
    port: 5672
amqp:
  default-queue: save-temperature
  reply-queue: save-temperature-reply
  dlq: save-temperature-dlq