spring:
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
    template:
      routing-key: test-temperaturedata
      exchange: test-meteodata_exchange
      default-receive-queue: test-temperaturedata
amqp:
  queue:
    name: test-temperaturedata