spring:
  rabbitmq:
    template:
      routing-key: test-temperaturedata
      exchange: test-meteodata_exchange
      default-receive-queue: test-temperaturedata
    listener:
      simple:
        auto-startup: false