spring:
  datasource:
    username: postgres
    password: postgres
    schema
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
    template:
      routing-key: test-temperaturedata
      exchange: test-meteodata_exchange
      default-receive-queue: test-temperaturedata
amqp:
  queue: test-temperaturedata
  dlq: test-temperaturedata.dlq
