spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/temperature-db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
    template:
      routing-key: test-temperaturedata
      exchange: test-meteodata_exchange
      default-receive-queue: test-temperaturedata